shallow_clone: true

image: Visual Studio 2017

platform: x64

skip_branch_with_pr: true

nuget:
    disable_publish_on_pr: true

# https://github.com/theochem/python-cython-ci-example/blob/master/.appveyor.yml
build_script:
    # - echo %VS140COMNTOOLS%
      # - '"%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%'
    # - appveyor DownloadFile https://aka.ms/vs/15/release/vs_community.exe
    # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    # - vs_community.exe --wait --quiet --norestart --add Microsoft.VisualStudio.Component.VC.Tools.14.12
    - '"C:\Miniconda3-x64\Scripts\activate.bat"'
    - echo "DEBUG SDK"
    - ver
    - dir "C:\Program Files (x86)\Windows Kits\10\Include"
    - echo "%LIB%"
    - echo "%CPATH%"
    - ps: $(Get-Item "hklm:\SOFTWARE\Microsoft\Microsoft SDKs\Windows").GetValue("CurrentVersion")
    - conda config --set always_yes yes
    - conda update -q conda
    - conda install -y --channel conda-forge cmake clangdev flang openblas perl
    - conda install -y --channel isuruf kitware-ninja
    - conda info -a
    # Must specify toolset version b/c after v14.12, we need Clang 6, and isuruf's flang is Clang 5.
    - call "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Auxiliary/Build/vcvarsall.bat" x64 -vcvars_ver=14.12
    - set "LIB=C:/Miniconda3-x64/Library/lib;%LIB%"
    - set "CPATH=C:/Miniconda3-x64/Library/include;%CPATH%"
    - echo "%LIB%"
    - echo "%CPATH%"
    - mkdir build
    - cd build
    - cmake .. -G "Ninja" -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DCMAKE_Fortran_COMPILER=flang -DCMAKE_INSTALL_PREFIX="C:/ipopt" -DCMAKE_BUILD_TYPE=Release
      # TODO install v14.12
      # https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-community?view=vs-2017
    - ninja install
    # TODO copy flang.lib etc.

artifacts:
    - path: C:/ipopt
